server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/om-data
  cloud:
    stream:
      binders:
        rabbit_binder:
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
