server:
  port: 8082

distributor:
  paymentConfiguration:
    CASH:
      paymentName: CASH
      paymentId: 1
    GATEWAY:
      paymentName: GATEWAY
      paymentId: 35
    CARD_TO_CONFIRM:
      paymentName: CARD_TO_CONFIRM
      paymentid: 27

  defaultDiscountConfiguration:
    description: External transaction discount
    discountId: 9999

spring:
  data:
    mongodb:
      uri: mongodb://mongodbdatabase:27017/distributor-data
  cloud:
    stream:
      binders:
        rabbit_binder:
          environment:
            spring:
              rabbitmq:
                host: rabbitserver
                port: 5672
           
