server:
  port: 8082
  
custom-feign:
  connectionTimeoutMillis: 5000
  readTimeoutMillis: 5000

distributor:
  saleType: externalTransaction
  defaultCadet: 1
  serverName: server1
  
  customJms:
    initialRedeliveryDelay: 3000
    redeliveryDelay: 4000
    maximumRedeliveries: 3
    persistenceDirectoryName: data
    
  paymentConfiguration:
    CASH:
      paymentName: CASH
      paymentId: 1
    GATEWAY:
      paymentName: GATEWAY
      paymentId: 35
    CARD_TO_CONFIRM:
      paymentName: CARD_TO_CONFIRM
      paymentid: 27
    CARD:
      paymentName: CARD_TO_CONFIRM
      paymentid: 27
  
  defaultDiscountConfiguration:
    description: External transaction discount
    discountId: 9999

  exportService:
    exportChannelName: oms
    url: /api/transaction/import

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/distributor-data
  activemq:
    brokerUrl: tcp://localhost:61617?jms.dispatchAsync=true
    pool:
      max-connections: 10
      enabled: true
      idle-timeout: 30
      max-sessions-per-connection: 500
  jms:
    listener:
      concurrency: 5
      max-concurrency: 10
      receive-timeout: 5s
  cloud:
    stream:
      rabbit:
        bindings:
          inputEvents:
            consumer:
              republish-to-dlq: true
      bindings:
        inputEvents:
          destination: exportSale
          binder: rabbit_binder
          group: exportSale-group
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 2000
            backOffMaxInterval: 2000
        outputEvents:
          destination: orderManager
          binder: rabbit_binder
          producer:
            requiredGroups: orderManager-group
      binders:
        rabbit_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
