server:
  port: 8082

distributor:
  saleType: externalTransaction
  
  customJms:
    initialRedeliveryDelay: 3000
    redeliveryDelay: 4000
    maximumRedeliveries: 3
    persistenceDirectoryName: data
    
  payments:
    RECAUDADO:
      paymentName: CASH
      paymentId: 1
      needCreditCardData: false
    MERPAY:
      paymentName: GATEWAY
      paymentId: 35
      needCreditCardData: true
    WEBPAY:
      paymentName: GATEWAY
      paymentId: 35
      needCreditCardData: true
    PAYU:
      paymentName: GATEWAY
      paymentId: 35
      needCreditCardData: true

  wirelessCardPayment:
    paymentName: MOBILE_POS_CARD
    paymentid: 27
    needCreditCardData: true
  
  defaultDiscountConfiguration:
    description: External transaction discount
    discountId: 9999

  exportService:
    exportChannelName: oms
    url: /api/transaction/import

feign:
  client:
    config:
      defautl:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/distributor-data
  activemq:
    brokerUrl: tcp://localhost:61617?jms.dispatchAsync=true
    pool:
      max-connections: 10
      enabled: true
      idle-timeout: 30
      max-sessions-per-connection: 500
  jms:
    listener:
      concurrency: 5
      max-concurrency: 10
      receive-timeout: 5s
  cloud:
    stream:
      rabbit:
        bindings:
          inputEvents:
            consumer:
              republish-to-dlq: true
      bindings:
        inputEvents:
          destination: exportSale
          binder: rabbit_binder
          group: exportSale-group
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 2000
            backOffMaxInterval: 2000
        outputEvents:
          destination: orderManager
          binder: rabbit_binder
          producer:
            requiredGroups: orderManager-group
      binders:
        rabbit_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
